### ISSUE TITLE
Change the installation mechanism

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [fholger/farcry_vrmod#1]
<details>
  <summary>Offtop</summary>
  First of all, thank you so much for this mod! @fholger, you're a brilliant! Hats off to you. It's just mind-blowing! 🤯 It's something I've been dreaming of for the past few years! Please continue to improve this mod. 🙏
</details>

Currently, the mod utilizes the built-in mod loading mechanism. The problem is that it doesn't allow to load more than one mod at a time. This means players won't be able to play other mods in VR.

What about something like just two *.bat files: one (e.g. `fcvr-install.bat`) replaces the game files, creating a backup, and the other (e.g. `fcvr-uninstall.bat`) restores the files from the backup?

**Comment by fholger** [comment]
If the mods in question ship with their own CryGame.dll, then it won't work either way. You can move the CryGame.dll in the CryVR folder to the game's bin32, though, and move the pak file to FCData if you want to set it up like that.

**Comment by pinoepel** [comment]
Is it possible that Uplay doesn't work? Installed it there but the game won't start in VR.
