### ISSUE TITLE
Way to Remap On Index Controllers to Not 'Click' Analog Sticks?

### ISSUE THREAD

**Issue by dakodeh** [fholger/farcry_vrmod#13]
This isn't so much an issue as it is a request; I see that multiple required actions (sprint, turn on light, etc..) are mapped to 'clicking in' the analog thumbsticks on the Index Controllers. Clicking in the analog sticks in such a way is a well-documented cause of stick drift on these controllers; would it be possible to get an alternate control scheme that allows mapping these actions to non-click bindings? (usually I recommend the digital thumbpads for these actions as they don't exist on other VR Motion controllers and therefore are usually are unused fair-game for such mappings).

**Comment by fholger** [comment]
All bindings are configurable via SteamVR controller bindings. I will not be offering rebinds from inside the game, as that would just be unnecessary (and significant) effort to duplicate that functionality.

**Comment by FluorescentHallucinogen** [comment]
> All bindings are configurable

It looks like not all of the actions from the game are available in SteamVR. E.g. I haven't found how to bind throwing a weapon (to pick up another one) to the controller button.

**Comment by FluorescentHallucinogen** [comment]
TBH, I didn't know that game actions can/should be customized via SteamVR. Maybe this should be added to the `ReadMe.md`?
