### ISSUE TITLE
low LOD draw distance 

### ISSUE THREAD

**Issue by benjamincheng10** [fholger/farcry_vrmod#14]
loving the mod, great job! while playing I noticed that the LOD distance for everything is really short, it seems like its also very short on flatscreen mode but just not as noticeable. Is there a way to be able to improve the LOD draw distance? I tried the configurator and some config file settings but nothing changes. apparently the 64bit patch has better LOD distance, but that patch doesn't seem to work with the VR mod. any ideas? right now for me the biggest flaw is the poor LOD draw distance.

**Comment by fholger** [comment]
There is a slider in the VR options for the vegetation distance. That should take care of the most egregious aspects of the LOD distance. It is not a complete fix, though, and unfortunately I'm not aware of easy fixes for the remaining issues.

**Comment by benjamincheng10** [comment]
ok thanks so much! i completely missed that slider and it did the trick! the vegetation LOD was the most egregious thing, the rest of the LOD stuff not big deal. great job on the mod, loving my tropical vacation!

**Comment by benjamincheng10** [comment]
the new option to draw distant objects works great, thanks! is there any way to make the texture LOD better as well?

**Comment by fholger** [comment]
I haven't found any meaningful way, and I'm afraid there may not be any way without engine changes, which are not accessible to this mod. You can set `e_detail_texture_min_fov 5` for a very minor improvement, but it's not enough.

**Comment by XavierHG** [comment]
I read somewhere that the levels (.cry) has it's own view distance set inside the map editor, but I can't confirm.
