### ISSUE TITLE
Decoupled vehicle camera option?

### ISSUE THREAD

**Issue by benjamincheng10** [fholger/farcry_vrmod#15]
hi, is there plans to implement decoupled camera turning in vehicles like how it's done in HL2 VR? great job on that BTW!!

**Comment by benjamincheng10** [comment]
great job on updating the mod, its getting better all the time!! Any plans to decouple the vehicle cameras tho? I mostly played on foot cause the vehicles makes me nauseous, but there's a forced vehicle section in the "swamp" map. i had to use dev mode to skip that level cause it was so dizzying and hard to aim with the ride jerking the camera around.

**Comment by fholger** [comment]
The option exists in the latest dev build.
