### ISSUE TITLE
Control mapping issues/ideas

### ISSUE THREAD

**Issue by benjamincheng10** [fholger/farcry_vrmod#16]
loving the game so far, found some of the control mapping to be awkward tho. Mostly involving vehicles, using the triggers for acceleration and reverse and having the A button to shoot creates such an awkward discrepancy between vehicles and on foot. 

I really like the old vehicle controls in HL2VR, where forward and back on the left thumbstick was mapped to vehicle movement and the shooting controls remain unchanged. I think it would make sense to use the right trigger for machine gun and left trigger for rockets in vehicles. 

also the auto-aim in vehicle is too strong and often gets stuck on a single target, a softer lock or option to disable would be nice. 

for grenades, it would be sweet if it was mapped to the left hand trigger, when not 2-handing a weapon. a grenade visual arc would be nice if that's possible. 

kind of nit-picking, just some ideas I think would make it smoother experience.

**Comment by fholger** [comment]
We got so much criticism about the old HL2VR vehicle controls that I decided to go with the new one straight away this time, and I'm afraid I just can't make everything 100% configurable all the time - it's just too much effort, and I have to manage my time.

You can certainly remap the grenades in the SteamVR controller bindings, though. Current grenade handling is a stopgap solution that I'm hoping to replace some time down the line.

**Comment by fholger** [comment]
For what it's worth, you can now unbind accelerate and brake actions for the vehicles, which will result in the mod using only the left stick for steering and acceleration.
