### ISSUE TITLE
New .exe results in no audio

### ISSUE THREAD

**Issue by mamefan** [fholger/farcry_vrmod#27]
I get audio at the splash screens but none at the main menu and game. Using the .bat file to launch instead fixes this.

**Comment by fholger** [comment]
Your game does not have focus. Switch to another app and back to the game.

**Comment by teddybear082** [comment]
I can confirm you just need to click on the far cry window to get it focused and audio is fine.

**Comment by mamefan** [comment]
I'd rather use the .bat file. Fewer steps.
