### ISSUE TITLE
Stamina draining too strong.

### ISSUE THREAD

**Issue by mfl3x** [fholger/farcry_vrmod#29]
Hey mate,
Latest 0.8 working flawlessly with scopes now. Great work!
Stamina and movement on sniper and missile launcher drains very fast and is moves very slow. Is this standard game speeds or can it be bumped up a bit so as not to feel like crawling to a stop? Have the same issue in vents where movement crawls to a very slow speed (almost stopped) and takes a painfully long time to complete.

**Comment by fholger** [comment]
I have not changed the base game attributes in this regard. But you can point your weapon downwards, and as long as you are not two-handing it, you will be able to move at full speed.

**Comment by ni1chigo2115** [comment]
> I have not changed the base game attributes in this regard. But you can point your weapon downwards, and as long as you are not two-handing it, you will be able to move at full speed.

I was sprinting and jogging, swinging my arms and legs (not trackers of course), but did I need to turn to my tongue?
That doesn't seem to work well with natural locomotion...
