### ISSUE TITLE
Could you add snap turning?

### ISSUE THREAD

**Issue by TrackBallPower** [fholger/farcry_vrmod#31]
The smooth turning makes me really nauseous, it would be really nice to have a snap turning feature available for this wonderful mod.

**Comment by fholger** [comment]
Check the options menu, it's already there :)

**Comment by TrackBallPower** [comment]
Stupid me, i wasn't aware that the options menu was actually the option menu of the farcry game itself :)
Thanks, love this mod by the way, great work!
