### ISSUE TITLE
Two handing weapons broken

### ISSUE THREAD

**Issue by Vicsamg** [fholger/farcry_vrmod#32]
Hello, just updated to the .8 update and I can't two hand weapons anymore.

**Comment by fholger** [comment]
Please provide a bit more detail, it works fine for me. What headset are you using? Are you left- or right-handed? What specifically happens or doesn't happen?

**Comment by Vicsamg** [comment]
Sure thing. Using the Quest 2 in virtual desktop (wireless). I'm left handed, I only need the weapon in the left hand, as in I don't need the analog sticks swapped.  The hand that shows empty is the right hand model and it will not grip the weapon at all. Did not have this issue in the older updates. I hold down the grip button and it does nothing. All other controls work perfectly except using scopes, which in believe only work when you get the weapons with both hands. So I essentially can't use any scopes right now.

**Comment by Vicsamg** [comment]
Ok, ok it's fixed now. I guess the update messed with my controller bindings? I just needed to reconfigure them again. Sorry about that, no issues now. Thank you?  Oh and let me just say this is the most fun game in VR!  Love your work,, you're awesome!!
