### ISSUE TITLE
Option to undo binocular or scope textures adapted by widescreen mod.

### ISSUE THREAD

**Issue by ni1chigo2115** [fholger/farcry_vrmod#33]
There is a widescreen support mod, but adapting it will cause problems with binoculars and scopes.
Wouldn't it be better to put in a material to force it back to the original TEXTURE?

**Comment by fholger** [comment]
I'm afraid when you are mixing mods you are on your own. I can't proactively solve every potential conflict that might occur. The mod targets unaltered installations of the game, if you want to add other mods on top, you'll have to take care to merge them as necessary.
