### ISSUE TITLE
Does AI see see through objects?

### ISSUE THREAD

**Issue by NoUserNameForYou** [fholger/farcry_vrmod#34]
Or do I need the far cry fix 32 from here? https://www.moddb.com/games/far-cry/downloads/far-cry-fix-32-bit

Would it work on the VR'd game?

**Comment by ni1chigo2115** [comment]
At least I am using this mod.
https://www.moddb.com/mods/tent-ai-bug-fix
Still, it's tricky to get an AI that looks like it has been clairvoyant from time to time.
(The lawn didn't help with stealth)

**Comment by NoUserNameForYou** [comment]
One of the users say "It fixes AI seeing through tents, but it doesn't fix AI seeing through WOODEN HOUSES on the islands. They see through several wooden walls and one-shot. "

**Comment by fholger** [comment]
The tent fix is included in the VR mod.

**Comment by NoUserNameForYou** [comment]
Thanks.

**Comment by NoUserNameForYou** [comment]
I just got destroyed by a minigun while he was behind wooden crates. 

https://youtu.be/0-pziS5nTFs?feature=shared&t=1029 -> 17:08 this is the place.

In my playthrough, the minigun's bullets went through the crates in front of him, looks like wood is still transparent.
