### ISSUE TITLE
Does -devmode still work? 

### ISSUE THREAD

**Issue by Vicsamg** [fholger/farcry_vrmod#36]
I've added the -devmode at the end of the target exe file (after the quotes), and it doesn't seem to work. Will it not, or did I do something wrong?

**Comment by fholger** [comment]
Yes, it does work. See the `FarCryVR_dev.bat` that you could also just use.

**Comment by Vicsamg** [comment]
Can't get it to work on the executable, but the batch file works. Didn't know about that batch file. Thanks!!
