### ISSUE TITLE
Other mods compatibility?

### ISSUE THREAD

**Issue by mcdermott87** [fholger/farcry_vrmod#48]
I would like to use other mods with this one, for example there's a [fix for AI wallhacking](https://www.moddb.com/mods/tent-ai-bug-fix). Are they compatible?

**Comment by fholger** [comment]
The tent fix is already included.

More generally, you can try, but the VR mod has its own code DLL and replaces a number of game scripts, including weapon and player scripts. Any mod that does the same will be in conflict.

**Comment by mcdermott87** [comment]
Thank you!
