### ISSUE TITLE
Uplay 

### ISSUE THREAD

**Issue by pinoepel** [fholger/farcry_vrmod#8]
Is it possible that Uplay doesn't work? Installed it there but the game won't start in VR.

**Comment by fholger** [comment]
I don't see any reason why it shouldn't work, but I don't have the Uplay version to verify. What exactly happens? Can you share the contents of the log.txt?

**Comment by fholger** [comment]
Had a chance to look into the Uplay version. It seems the FarCry launcher functions slightly differently there, and that's confusing the launcher bat files. You can try editing the `FarCryVR.bat` file and removing the final line (`erase d3d9.dll`), save it and then try launching it again. I got it to work that way, at least.

**Comment by Fearganainim** [comment]
Any one running this from an ISO and if so how? Mine won't launch.

**Comment by hoerzers** [comment]
I have removed the erase d3d9.dll line from the script and the game starts in VR OK but as soon as I start the campaign it crashes with some access violation. Is this something that can be fixed? TIA
