### ISSUE TITLE
The memory could not be "read"

### ISSUE THREAD

**Issue by HappyStoat** [fholger/farcry_vrmod#9]
Hi there, 
right after I start the FarCryVR.bat, I get this error, in parallel to the black screen (nothing happends): 

Logged at Tuesday, August 01, 2023 15:53:50
FileVersion: 1.1.0.1230
ProductVersion: 1.1.0.1230

Exception Code: 0xC0000005
Exception Addr: 0x0023:0x38010FA3
Exception Module: <Unknown>
Exception Description: EXCEPTION_ACCESS_VIOLATION, Attempt to read from address 0x0000000C
The memory could not be "read"

Call Stack Trace:
 2) function=0x38010FA3
 1) function=0x0

Haha this takes me back, when I was working with the Cryengine 1 in 2004. At that time you often got to see this window.

I installed the game via stream. Even after a clean reinstall it crashes.
Maybe it's because of Vridge, I use this software to test It on my smartphone. Maybe you have an idea. The normal Game works without problems. I use Windows 11 and a Nvidia GTX1650.

**Comment by HappyStoat** [comment]
Ah and of course thanks for your nice work!!! :)

**Comment by HappyStoat** [comment]
This is what the log said (May be its really the Vridge...): 
...
Physics initialization
MovieSystem initialization
Renderer initialization
System: INFO: DirectX 12.0 installed
System: VideoCard Detected: Intel (Unknown)
Direct3D9 driver is creating...
Error: Couldn't find any suitable device (Unknown)
<CRITICAL ERROR>
Exception: 0xC0000005, at Address: 0x0023:0x38010FA3
Exception Code: 0xC0000005
Exception Addr: 0x0023:0x38010FA3
Exception Module: <Unknown>
Exception Description: Attempt to read from address 0x0000000C

**Comment by fholger** [comment]
The log says it found an "Intel" GPU. If you really only have an Intel iGPU or an ARC card, there is a high chance that this will simply not work. If you do have an NVIDIA or AMD dedicated GPU, you may need to force the game to use it, instead, as it appears it's selecting the wrong GPU.

**Comment by HappyStoat** [comment]
The Sandbox Editor works as well, by the way

**Comment by fholger** [comment]
You mean it still says "Intel" GPU? Then it is still selecting the wrong GPU.
You could try to add the following line in the FarCryVR.bat at the beginning:
  `set DXVK_FILTER_DEVICE_NAME=NVIDIA`

Not sure what else to suggest.

**Comment by HappyStoat** [comment]
I will give it a try, but perhaps only the GPUs found are listed in the logs, regardless of which one is actually used. 
This is what the log says when I completly disable the intel GPU: 

Physics initialization
MovieSystem initialization
Renderer initialization
System: INFO: DirectX 12.0 installed
System: VideoCard Detected: Unknown ()
Direct3D9 driver is creating...
Error: Couldn't find any suitable device (Unknown)
<CRITICAL ERROR>
Exception: 0xC0000005, at Address: 0x0023:0x38010FA3
Exception Code: 0xC0000005
Exception Addr: 0x0023:0x38010FA3
Exception Module: <Unknown>
Exception Description: Attempt to read from address 0x0000000C

**Comment by HappyStoat** [comment]
I will try a different driver as well

**Comment by HappyStoat** [comment]
Okay it really was the graphics driver, it's working now...
Thank you for your help!!

**Comment by Dimster-glitch** [comment]
> I will try a different driver as well

I am sorry to bother you, I seem to have the same problem. Same messages (Unknown),  Direct3D9 suitable device not found. My only GPU is AMD RX6600. What do you mean by "trying a different driver"? Sorry if the question is stupid.
